/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./PropertyTypeItem.module.css";

const PropertyTypeItem = ({ name, icon }) => {
  return (
    <div className={styles.typeItem}>
      <img src={icon} alt="" className={styles.typeIcon} />
      <span className={styles.typeName}>{name}</span>
    </div>
  );
};

export default PropertyTypeItem;
